export const SET_USER_INFO = 'SET_USER_INFO';
export const GET_QUEUE_INFO = 'GET_QUEUE_INFO';
export const GET_PARTY_INFO = 'GET_PARTY_INFO';
export const INCREMENT_PARTY_SIZE = 'INCREMENT_PARTY_SIZE';
export const DECREMENT_PARTY_SIZE = 'DECREMENT_PARTY_SIZE';
