export const SET_USER_INFO = 'SET_USER_INFO';
export const GET_QUEUE_INFO = 'GET_QUEUE_INFO';
export const GET_PARTY_INFO = 'GET_PARTY_INFO';
export const UPDATE_QUEUE_INFO = 'UPDATE_QUEUE_INFO';
export const UPDATE_PARTY_INFO = 'UPDATE_PARTY_INFO';
export const CHANGE_PARTY_SIZE = 'CHANGE_PARTY_SIZE';
export const DEQUEUE = 'DEQUEUE';
